name: Release macOS DMG

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      arch:
        description: "Architecture to build (arm64 | x64 | both)"
        required: false
        default: "both"

permissions:
  contents: read

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python 3.11 for node-gyp
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python build deps (setuptools shim for distutils)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          echo "python=$(which python3)" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          npm_config_python: ${{ env.python }}
        run: npm ci

      - name: Build app (ts + vite)
        run: npm run build

      - name: Build DMG(s) (no publish)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: |
          ARCH_INPUT="${{ github.event.inputs.arch }}"
          if [ -z "$ARCH_INPUT" ] || [ "$ARCH_INPUT" = "both" ]; then
            FLAGS="--x64 --arm64"
          elif [ "$ARCH_INPUT" = "arm64" ]; then
            FLAGS="--arm64"
          elif [ "$ARCH_INPUT" = "x64" ]; then
            FLAGS="--x64"
          else
            echo "Unknown arch input: $ARCH_INPUT" && exit 1
          fi
          echo "Building for: $FLAGS"
          npx electron-builder --mac dmg $FLAGS --publish never

      # Optional: upload build artifacts for debugging even if publish fails
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dmgs
          path: release/*.dmg

  release-mac:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    permissions:
      contents: write
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python 3.11 for node-gyp
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python build deps (setuptools shim for distutils)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          echo "python=$(which python3)" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          npm_config_python: ${{ env.python }}
        run: npm ci

      - name: Build app (ts + vite)
        run: npm run build

      - name: Detect notarization secrets
        run: |
          if [ -n "${{ secrets.APPLE_API_KEY }}" ] && [ -n "${{ secrets.APPLE_API_KEY_ID }}" ] && [ -n "${{ secrets.APPLE_API_ISSUER }}" ]; then
            echo "HAS_APPLE_API=true" >> $GITHUB_ENV
          else
            echo "HAS_APPLE_API=false" >> $GITHUB_ENV
          fi

      - name: Prepare Apple API key (if provided)
        if: env.HAS_APPLE_API == 'true'
        run: |
          echo "${{ secrets.APPLE_API_KEY }}" > ./apple_api_key.p8
          echo "APPLE_API_KEY=$(pwd)/apple_api_key.p8" >> $GITHUB_ENV
          echo "APPLE_API_KEY_ID=${{ secrets.APPLE_API_KEY_ID }}" >> $GITHUB_ENV
          echo "APPLE_API_ISSUER=${{ secrets.APPLE_API_ISSUER }}" >> $GITHUB_ENV

      - name: Build and publish signed DMG(s)
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_API_KEY: ${{ env.APPLE_API_KEY }}
          APPLE_API_KEY_ID: ${{ env.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ env.APPLE_API_ISSUER }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ARCH_INPUT="${{ github.event.inputs.arch }}"
          if [ -z "$ARCH_INPUT" ] || [ "$ARCH_INPUT" = "both" ]; then
            FLAGS="--x64 --arm64"
          elif [ "$ARCH_INPUT" = "arm64" ]; then
            FLAGS="--arm64"
          elif [ "$ARCH_INPUT" = "x64" ]; then
            FLAGS="--x64"
          else
            echo "Unknown arch input: $ARCH_INPUT" && exit 1
          fi
          echo "Building signed for: $FLAGS"
          npx electron-builder --mac dmg $FLAGS --publish always

      - name: Staple notarization (best-effort)
        if: always()
        run: |
          set -e
          # Staple apps
          for APP in release/mac*/emdash.app; do
            if [ -d "$APP" ]; then
              xcrun stapler staple "$APP" || true
            fi
          done
          # Staple DMGs
          for DMG in release/*.dmg; do
            if [ -f "$DMG" ]; then
              xcrun stapler staple "$DMG" || true
            fi
          done
